package HBM;
// Generated 26-nov-2011 14:00:41 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Autor generated by hbm2java
 */
@Entity
@Table(name="autor"
    ,catalog="jbiblos"
)
public class Autor  implements java.io.Serializable {


     private Short idAutor;
     private String nombreAutor;
     private String apellido1Autor;
     private String apellido2Autor;
     private Set<Titulo> titulos = new HashSet<Titulo>(0);

    public Autor() {
    }

	
    public Autor(String nombreAutor, String apellido1Autor) {
        this.nombreAutor = nombreAutor;
        this.apellido1Autor = apellido1Autor;
    }
    public Autor(String nombreAutor, String apellido1Autor, String apellido2Autor, Set<Titulo> titulos) {
       this.nombreAutor = nombreAutor;
       this.apellido1Autor = apellido1Autor;
       this.apellido2Autor = apellido2Autor;
       this.titulos = titulos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_autor", unique=true, nullable=false)
    public Short getIdAutor() {
        return this.idAutor;
    }
    
    public void setIdAutor(Short idAutor) {
        this.idAutor = idAutor;
    }
    
    @Column(name="nombre_autor", nullable=false, length=35)
    public String getNombreAutor() {
        return this.nombreAutor;
    }
    
    public void setNombreAutor(String nombreAutor) {
        this.nombreAutor = nombreAutor;
    }
    
    @Column(name="apellido1_autor", nullable=false, length=35)
    public String getApellido1Autor() {
        return this.apellido1Autor;
    }
    
    public void setApellido1Autor(String apellido1Autor) {
        this.apellido1Autor = apellido1Autor;
    }
    
    @Column(name="apellido2_autor", length=45)
    public String getApellido2Autor() {
        return this.apellido2Autor;
    }
    
    public void setApellido2Autor(String apellido2Autor) {
        this.apellido2Autor = apellido2Autor;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinTable(name="titulo_has_autor", catalog="jbiblos", joinColumns = { 
        @JoinColumn(name="autor_id_autor", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="titulo_dewey_categoria_dewey", nullable=false, updatable=false) })
    public Set<Titulo> getTitulos() {
        return this.titulos;
    }
    
    public void setTitulos(Set<Titulo> titulos) {
        this.titulos = titulos;
    }




}


