package HBM;
// Generated 26-nov-2011 14:00:41 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Dewey generated by hbm2java
 */
@Entity
@Table(name="dewey"
    ,catalog="jbiblos"
)
public class Dewey  implements java.io.Serializable {


     private short categoriaDewey;
     private String nombreCategoriaDewey;
     private Set<Titulo> titulos = new HashSet<Titulo>(0);

    public Dewey() {
    }

	
    public Dewey(short categoriaDewey, String nombreCategoriaDewey) {
        this.categoriaDewey = categoriaDewey;
        this.nombreCategoriaDewey = nombreCategoriaDewey;
    }
    public Dewey(short categoriaDewey, String nombreCategoriaDewey, Set<Titulo> titulos) {
       this.categoriaDewey = categoriaDewey;
       this.nombreCategoriaDewey = nombreCategoriaDewey;
       this.titulos = titulos;
    }
   
     @Id 
    
    @Column(name="categoria_dewey", unique=true, nullable=false)
    public short getCategoriaDewey() {
        return this.categoriaDewey;
    }
    
    public void setCategoriaDewey(short categoriaDewey) {
        this.categoriaDewey = categoriaDewey;
    }
    
    @Column(name="nombre_categoria_dewey", nullable=false, length=20)
    public String getNombreCategoriaDewey() {
        return this.nombreCategoriaDewey;
    }
    
    public void setNombreCategoriaDewey(String nombreCategoriaDewey) {
        this.nombreCategoriaDewey = nombreCategoriaDewey;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="dewey")
    public Set<Titulo> getTitulos() {
        return this.titulos;
    }
    
    public void setTitulos(Set<Titulo> titulos) {
        this.titulos = titulos;
    }

    @Override
    public String toString() {
        return categoriaDewey + " - "+nombreCategoriaDewey;
    }




}


