package HBM;
// Generated 26-nov-2011 14:00:41 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Editorial generated by hbm2java
 */
@Entity
@Table(name="editorial"
    ,catalog="jbiblos"
)
public class Editorial  implements java.io.Serializable {


     private Short idEditorial;
     private String nombreEditorial;
     private Set<Titulo> titulos = new HashSet<Titulo>(0);

    public Editorial() {
    }

	
    public Editorial(String nombreEditorial) {
        this.nombreEditorial = nombreEditorial;
    }
    public Editorial(String nombreEditorial, Set<Titulo> titulos) {
       this.nombreEditorial = nombreEditorial;
       this.titulos = titulos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_editorial", unique=true, nullable=false)
    public Short getIdEditorial() {
        return this.idEditorial;
    }
    
    public void setIdEditorial(Short idEditorial) {
        this.idEditorial = idEditorial;
    }
    
    @Column(name="nombre_editorial", nullable=false, length=45)
    public String getNombreEditorial() {
        return this.nombreEditorial;
    }
    
    public void setNombreEditorial(String nombreEditorial) {
        this.nombreEditorial = nombreEditorial;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="editorial")
    public Set<Titulo> getTitulos() {
        return this.titulos;
    }
    
    public void setTitulos(Set<Titulo> titulos) {
        this.titulos = titulos;
    }




}


