package HBM;
// Generated 26-nov-2011 14:00:41 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Idioma6391 generated by hbm2java
 */
@Entity
@Table(name="idioma_639_1"
    ,catalog="jbiblos"
)
public class Idioma6391  implements java.io.Serializable {


     private String idIdioma6391;
     private String idioma6391;
     private Set<Titulo> titulos = new HashSet<Titulo>(0);

    public Idioma6391() {
    }

	
    public Idioma6391(String idIdioma6391, String idioma6391) {
        this.idIdioma6391 = idIdioma6391;
        this.idioma6391 = idioma6391;
    }
    public Idioma6391(String idIdioma6391, String idioma6391, Set<Titulo> titulos) {
       this.idIdioma6391 = idIdioma6391;
       this.idioma6391 = idioma6391;
       this.titulos = titulos;
    }
   
     @Id 
    
    @Column(name="id_idioma_639_1", unique=true, nullable=false, length=2)
    public String getIdIdioma6391() {
        return this.idIdioma6391;
    }
    
    public void setIdIdioma6391(String idIdioma6391) {
        this.idIdioma6391 = idIdioma6391;
    }
    
    @Column(name="idioma_639_1", nullable=false, length=45)
    public String getIdioma6391() {
        return this.idioma6391;
    }
    
    public void setIdioma6391(String idioma6391) {
        this.idioma6391 = idioma6391;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="idioma6391")
    public Set<Titulo> getTitulos() {
        return this.titulos;
    }
    
    public void setTitulos(Set<Titulo> titulos) {
        this.titulos = titulos;
    }




}


