package HBM;
// Generated 26-nov-2011 14:00:41 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Titulo generated by hbm2java
 */
@Entity
@Table(name="titulo"
    ,catalog="jbiblos"
)
public class Titulo  implements java.io.Serializable {


     private TituloId id;
     private Editorial editorial;
     private Dewey dewey;
     private Idioma6391 idioma6391;
     private String nombreTitulo;
     private Long isbn;
     private Date fechaPublicacion;
     private Date fechaAdquisicion;
     private String sinopsis;
     private Short numPaginas;
     private byte edicion;
     private Set<Autor> autors = new HashSet<Autor>(0);

    public Titulo() {
    }

	
    public Titulo(TituloId id, Editorial editorial, Dewey dewey, Idioma6391 idioma6391, String nombreTitulo, byte edicion) {
        this.id = id;
        this.editorial = editorial;
        this.dewey = dewey;
        this.idioma6391 = idioma6391;
        this.nombreTitulo = nombreTitulo;
        this.edicion = edicion;
    }
    public Titulo(TituloId id, Editorial editorial, Dewey dewey, Idioma6391 idioma6391, String nombreTitulo, Long isbn, Date fechaPublicacion, Date fechaAdquisicion, String sinopsis, Short numPaginas, byte edicion, Set<Autor> autors) {
       this.id = id;
       this.editorial = editorial;
       this.dewey = dewey;
       this.idioma6391 = idioma6391;
       this.nombreTitulo = nombreTitulo;
       this.isbn = isbn;
       this.fechaPublicacion = fechaPublicacion;
       this.fechaAdquisicion = fechaAdquisicion;
       this.sinopsis = sinopsis;
       this.numPaginas = numPaginas;
       this.edicion = edicion;
       this.autors = autors;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="deweyCategoriaDewey", column=@Column(name="dewey_categoria_dewey", nullable=false) ), 
        @AttributeOverride(name="idApellido", column=@Column(name="id_apellido", nullable=false, length=3) ), 
        @AttributeOverride(name="idTitulo", column=@Column(name="id_titulo", nullable=false, length=3) ) } )
    public TituloId getId() {
        return this.id;
    }
    
    public void setId(TituloId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="editorial_id_editorial", nullable=false)
    public Editorial getEditorial() {
        return this.editorial;
    }
    
    public void setEditorial(Editorial editorial) {
        this.editorial = editorial;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="dewey_categoria_dewey", nullable=false, insertable=false, updatable=false)
    public Dewey getDewey() {
        return this.dewey;
    }
    
    public void setDewey(Dewey dewey) {
        this.dewey = dewey;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idioma_639_1_id_idioma_639_1", nullable=false)
    public Idioma6391 getIdioma6391() {
        return this.idioma6391;
    }
    
    public void setIdioma6391(Idioma6391 idioma6391) {
        this.idioma6391 = idioma6391;
    }
    
    @Column(name="nombre_titulo", nullable=false, length=50)
    public String getNombreTitulo() {
        return this.nombreTitulo;
    }
    
    public void setNombreTitulo(String nombreTitulo) {
        this.nombreTitulo = nombreTitulo;
    }
    
    @Column(name="isbn")
    public Long getIsbn() {
        return this.isbn;
    }
    
    public void setIsbn(Long isbn) {
        this.isbn = isbn;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="fecha_publicacion", length=10)
    public Date getFechaPublicacion() {
        return this.fechaPublicacion;
    }
    
    public void setFechaPublicacion(Date fechaPublicacion) {
        this.fechaPublicacion = fechaPublicacion;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_adquisicion", length=19)
    public Date getFechaAdquisicion() {
        return this.fechaAdquisicion;
    }
    
    public void setFechaAdquisicion(Date fechaAdquisicion) {
        this.fechaAdquisicion = fechaAdquisicion;
    }
    
    @Column(name="sinopsis", length=65535)
    public String getSinopsis() {
        return this.sinopsis;
    }
    
    public void setSinopsis(String sinopsis) {
        this.sinopsis = sinopsis;
    }
    
    @Column(name="num_paginas")
    public Short getNumPaginas() {
        return this.numPaginas;
    }
    
    public void setNumPaginas(Short numPaginas) {
        this.numPaginas = numPaginas;
    }
    
    @Column(name="edicion", nullable=false)
    public byte getEdicion() {
        return this.edicion;
    }
    
    public void setEdicion(byte edicion) {
        this.edicion = edicion;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinTable(name="titulo_has_autor", catalog="jbiblos", joinColumns = { 
        @JoinColumn(name="titulo_dewey_categoria_dewey", nullable=false, updatable=false), 
        @JoinColumn(name="titulo_id_apellido", nullable=false, updatable=false), 
        @JoinColumn(name="titulo_id_titulo", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="autor_id_autor", nullable=false, updatable=false) })
    public Set<Autor> getAutors() {
        return this.autors;
    }
    
    public void setAutors(Set<Autor> autors) {
        this.autors = autors;
    }




}


