/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VistaGLogin.java
 *
 * Created on 23-nov-2011, 18:55:38
 */
package Vista;

import Controlador.Controlador;
import Controlador.Evento;
import Controlador.GestorEventos;
import Controlador.TipoEvento;
import Modelo.Login;
import Modelo.Usuario;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.beans.PropertyChangeEvent;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;


/**
 *
 * @author nanohp
 */
public class VistaGLogin extends javax.swing.JFrame implements GestorEventos, GestionarModelo {

    private Controlador controlador;
    private GestorEventos padre;

    /** Creates new form VistaGLogin */
    public VistaGLogin(GestorEventos padre, Controlador controlador) {
        this.padre = padre;
        this.controlador = controlador;
        initComponents();
        inicializaComponentesPropios();
    }

    public void inicializaComponentesPropios() {
      

    }

    public void paint(Graphics g) {
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTFUsuario = new javax.swing.JTextField();
        jTFClave = new javax.swing.JPasswordField();
        jBotonLoginAceptar = new javax.swing.JButton();
        jBotonLoginCancelar = new javax.swing.JButton();
        jLabelJBiblos = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxLookAndFeel = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bienvenido a JBiblos - Login");
        setAlwaysOnTop(true);
        setResizable(false);

        jLabel1.setText("Usuario");

        jLabel2.setText("Clave");

        jTFUsuario.setColumns(10);

        jTFClave.setColumns(10);

        jBotonLoginAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/User_info_16.png"))); // NOI18N
        jBotonLoginAceptar.setText("Aceptar");
        jBotonLoginAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonLoginAceptarActionPerformed(evt);
            }
        });

        jBotonLoginCancelar.setText("Cancelar");
        jBotonLoginCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonLoginCancelarActionPerformed(evt);
            }
        });

        jLabelJBiblos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelJBiblos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/catalogo_64.png"))); // NOI18N

        jLabel3.setText("JBiblos");

        jComboBoxLookAndFeel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "GTK", "Metal", "System", "Motif" }));

        jLabel4.setText("L&F");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTFUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTFClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jComboBoxLookAndFeel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelJBiblos)
                    .addComponent(jLabel3))
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jBotonLoginAceptar)
                .addGap(18, 18, 18)
                .addComponent(jBotonLoginCancelar)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxLookAndFeel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBotonLoginCancelar)
                            .addComponent(jBotonLoginAceptar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabelJBiblos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBotonLoginAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonLoginAceptarActionPerformed
        Login login = new Login(jTFUsuario.getText().trim(), jTFClave.getText().trim());
        login.setLookAndFeel((String)jComboBoxLookAndFeel.getSelectedItem());
        
        
        controlador.procesarEvento(new Evento(TipoEvento.LOGIN, login, this));
    }//GEN-LAST:event_jBotonLoginAceptarActionPerformed

    private void jBotonLoginCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonLoginCancelarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBotonLoginCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;




                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaGLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaGLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaGLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaGLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                //new VistaGLogin().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBotonLoginAceptar;
    private javax.swing.JButton jBotonLoginCancelar;
    private javax.swing.JComboBox jComboBoxLookAndFeel;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelJBiblos;
    private javax.swing.JPasswordField jTFClave;
    private javax.swing.JTextField jTFUsuario;
    // End of variables declaration//GEN-END:variables

    @Override
    public void modelPropertyChange(PropertyChangeEvent evt) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void procesarEvento(Evento evento) {
        Object info = evento.getInfo();

        switch (evento.getTipoEvento()) {

            case LOGIN_OK:
                if (info.getClass().getName().startsWith("Modelo.Usuario")) {
                    setVisible(false);
                    System.out.println("--------"+jComboBoxLookAndFeel.getSelectedItem());
                    ((Usuario)info).setLookAndFeel((String)jComboBoxLookAndFeel.getSelectedItem());
                    padre.procesarEvento(new Evento(TipoEvento.FIJAR_LYL, jComboBoxLookAndFeel.getSelectedItem()));
                    padre.procesarEvento(new Evento(TipoEvento.LOGIN_OK, info));
                } else {
                    assert false : info.getClass().getName() + " clase no valida";
                }
                break;
            case LOGIN_FALLO:
                JOptionPane.showMessageDialog(this,
                        "Fallo en el usuario / clave.",
                        "Error de acceso",
                        JOptionPane.ERROR_MESSAGE);
                break;
            default:
                throw new AssertionError();
        }

    }

    @Override
    public void fijarModelo(Object object) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public Object obtenerModelo() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void limpiarModelo() {
        jTFUsuario.setText("");
        jTFClave.setText("");
    }

    @Override
    public void setEditable(boolean setEditable) {
        throw new UnsupportedOperationException("Not supported yet.");
    }
}
