/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VistaGCGeneral.java
 *
 * Created on 23-nov-2011, 23:27:34
 */
package Vista;

import HBM.Autor;
import HBM.Dewey;
import HBM.Titulo;
import Modelo.Catalogo;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;
import java.util.List;
import java.util.Set;
import javax.swing.JDesktopPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nanohp
 */
public class VistaGCGeneral extends javax.swing.JInternalFrame implements GestionarModelo {

    VistaGFichaTitulo vGFichaTitulo;
    CatalogoTableModel catalogoTableModel;
    Catalogo catalogo;
    List<Dewey> listaCategoriasDewey;
    private JDesktopPane jDesktopPane;

    /** Creates new form VistaGCGeneral */
    public VistaGCGeneral(List<Dewey> listaCategoriasDewey, JDesktopPane jDesktopPane) {
        this.listaCategoriasDewey = listaCategoriasDewey;
        this.jDesktopPane = jDesktopPane;

        initComponents();
        inicializaComponentesPropios();
    }

    private void inicializaComponentesPropios() {
        vGFichaTitulo = new VistaGFichaTitulo(listaCategoriasDewey);
        jDesktopPane.add(vGFichaTitulo);
        jButtonMostrarFicha.setVisible(false);
    }

    // Implementacion de los metodos de 'GestionarModelo'
    @Override
    public void fijarModelo(Object object) {
        this.catalogo = (Catalogo) object;
        catalogoTableModel = new CatalogoTableModel(catalogo.getCatalogo().values());
        jTableCatalogo.setModel(catalogoTableModel);
        jTableCatalogo.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);

    }

    @Override
    public Catalogo obtenerModelo() {
        return catalogo;
    }

    @Override
    public void limpiarModelo() {
        catalogo = null;
    }

    @Override
    public void setEditable(boolean setEditable) {
    }

    class CatalogoTableModel extends DefaultTableModel {

        Object[] encabezado = {"Código", "F publicación", "Edicion", "Editorial", "Idioma", "Autor"};
        //private Collection<Titulo> titulos;
        private ArrayList<Titulo> listaTitulos = new ArrayList<Titulo>();

        public CatalogoTableModel(Collection<Titulo> titulos) {
            super();
            //this.titulos = titulos;
            Object data[][] = new Object[titulos.size()][encabezado.length];

            int i = 0;
            for (Titulo titulo : titulos) {
                int j = 0;
                // Extraemos los apellidos
                data[i][j++] = titulo.getId().getDeweyCategoriaDewey() + "-" + titulo.getId().getIdApellido() + "-" + titulo.getId().getIdTitulo();
                data[i][j++] = titulo.getFechaPublicacion();
                data[i][j++] = titulo.getEdicion();
                data[i][j++] = titulo.getEditorial().getNombreEditorial();
                data[i][j++] = titulo.getIdioma6391().getIdioma6391();
                Set<Autor> autores = titulo.getAutors();
                Iterator<Autor> it = autores.iterator();
                int numAutores = autores.size();
                String autoresStr = "";
                if (numAutores > 0) {
                    Autor autor = it.next();
                    autoresStr = autor.getApellido1Autor() + ", " + autor.getNombreAutor();
                    if (numAutores > 1) {
                        autoresStr += " ...";
                    }
                } else {
                    autoresStr = "Sin autor";
                }

                data[i][j++] = autoresStr;

                listaTitulos.add(titulo);
                i++;
            }
            setDataVector(data, encabezado);
        }

        public void addTitulo(Titulo titulo) {
            //titulos.add(titulo);
            listaTitulos.add(titulo);
        }

        public Titulo getTitulo(int pos) {
            return listaTitulos.get(pos);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCatalogo = new javax.swing.JTable();
        jButtonAceptar = new javax.swing.JButton();
        jButtonMostrarFicha = new javax.swing.JButton();

        setTitle("Catálogo general");

        jTableCatalogo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableCatalogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCatalogoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCatalogo);

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jButtonMostrarFicha.setText("Mostrar ficha");
        jButtonMostrarFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarFichaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jButtonAceptar)
                        .addGap(40, 40, 40)
                        .addComponent(jButtonMostrarFicha))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAceptar)
                    .addComponent(jButtonMostrarFicha)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jTableCatalogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCatalogoMouseClicked
        int pos = jTableCatalogo.getSelectedRow();
        boolean visible = pos > -1 ? true : false;
        jButtonMostrarFicha.setVisible(visible);
        //vGFichaTitulo.setVisible(true);
    }//GEN-LAST:event_jTableCatalogoMouseClicked

    private void jButtonMostrarFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarFichaActionPerformed
        int filaSeleccionada = jTableCatalogo.getSelectedRow();
        System.out.println(filaSeleccionada);
        if (filaSeleccionada > -1) {
            System.out.println("--:" + catalogoTableModel.getTitulo(filaSeleccionada));
            vGFichaTitulo.fijarModelo(catalogoTableModel.getTitulo(filaSeleccionada));
            vGFichaTitulo.setVisible(true);
        }

    }//GEN-LAST:event_jButtonMostrarFichaActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonMostrarFicha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCatalogo;
    // End of variables declaration//GEN-END:variables
}
