/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VistaGCConcreta.java
 *
 * Created on 28-nov-2011, 13:26:44
 */
package Vista;

import Controlador.Controlador;
import Controlador.Evento;
import Controlador.Observador;
import Controlador.TipoEvento;
import HBM.Dewey;
import HBM.TituloId;
import Modelo.CategoriaDewey;
import Modelo.CodDewey;
import java.util.List;
import javax.swing.JDesktopPane;

/**
 *
 * @author tutto
 */
public class VistaGCConcreta extends javax.swing.JInternalFrame {

    private TituloId tituloId;
    private Controlador controlador;
    private Observador observadorPadre;
    List<Dewey> listaCategoriasDewey;

    /** Creates new form VistaGCConcreta */
    public VistaGCConcreta(Observador padre, Controlador controlador, List<Dewey> listaCategoriasDewey) {
        this.observadorPadre = padre;
        this.controlador = controlador;
        this.listaCategoriasDewey = listaCategoriasDewey;
        initComponents();
        inicializaComponentesPropios();
    }

    private void inicializaComponentesPropios() {
        jComboBoxCategoriasDewey.addItem(new String("Seleccione Categoría"));
        for (Dewey dewey : listaCategoriasDewey) {
            //jComboBoxCategoriasDewey.addItem(dewey.getCategoriaDewey() + " - " + dewey.getNombreCategoriaDewey());
            jComboBoxCategoriasDewey.addItem(dewey);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldCodApellido = new javax.swing.JTextField();
        jTextFieldCodTitulo = new javax.swing.JTextField();
        jButtonReset = new javax.swing.JButton();
        javax.swing.JButton jButtonCancelar = new javax.swing.JButton();
        jComboBoxCategoriasDewey = new javax.swing.JComboBox();

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jLabel1.setText("Dewey");

        jTextFieldCodApellido.setColumns(3);

        jTextFieldCodTitulo.setColumns(3);

        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jComboBoxCategoriasDewey.setModel(new javax.swing.DefaultComboBoxModel());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jButtonBuscar)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButtonCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxCategoriasDewey, 0, 164, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jTextFieldCodApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldCodTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxCategoriasDewey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCodApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCodTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBuscar)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonReset))
                .addGap(74, 74, 74))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        jComboBoxCategoriasDewey.setSelectedIndex(0);
        jTextFieldCodApellido.setText("");
        jTextFieldCodTitulo.setText("");
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed

        // El boton SOLO tiene efecto si TODOS los campos del código dewey están completos
        if (jComboBoxCategoriasDewey.getSelectedIndex() > 0
                && !jTextFieldCodApellido.getText().equals("")
                && !jTextFieldCodTitulo.getText().equals("")) {
            Dewey dewey = (Dewey) jComboBoxCategoriasDewey.getSelectedItem();

            tituloId = new TituloId(dewey.getCategoriaDewey(),
                    jTextFieldCodApellido.getText(), jTextFieldCodTitulo.getText());
            controlador.gestionarEvento(new Evento(TipoEvento.CONSULTA_CATALOGO_CONCRETA, tituloId, observadorPadre));
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JComboBox jComboBoxCategoriasDewey;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextFieldCodApellido;
    private javax.swing.JTextField jTextFieldCodTitulo;
    // End of variables declaration//GEN-END:variables
}
