/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VistaGCGeneral.java
 *
 * Created on 23-nov-2011, 23:27:34
 */
package Vista;

import HBM.Autor;
import HBM.Dewey;
import HBM.Titulo;
import Modelo.Catalogo;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;
import java.util.List;
import java.util.Set;
import javax.swing.JDesktopPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.apache.commons.lang3.text.WordUtils;

/**
 *
 * @author nanohp
 */
public class VistaGCGeneral extends javax.swing.JInternalFrame implements GestionarModelo {

    VistaGFichaTitulo vGFichaTitulo;
    CatalogoTableModel catalogoTableModel;
    List<Dewey> listaCategoriasDewey;
    private JDesktopPane jDesktopPane;

    /** Creates new form VistaGCGeneral */
    public VistaGCGeneral(List<Dewey> listaCategoriasDewey, JDesktopPane jDesktopPane) {
        this.listaCategoriasDewey = listaCategoriasDewey;
        this.jDesktopPane = jDesktopPane;

        initComponents();
        inicializaComponentesPropios();
    }

    private void inicializaComponentesPropios() {
        vGFichaTitulo = new VistaGFichaTitulo(listaCategoriasDewey);
        jDesktopPane.add(vGFichaTitulo);
        jButtonMostrarFicha.setVisible(false);
    }

    // Implementacion de los metodos de 'GestionarModelo'
    @Override
    public void fijarModelo(Object object) {
        assert (object.getClass().getName().endsWith(".Catalogo")) : "fijarModelo: clase suminastrada invalida";

        catalogoTableModel = new CatalogoTableModel((Catalogo) object);
        jTableCatalogo.setModel(catalogoTableModel);
        jTableCatalogo.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);

    }

    @Override
    public CatalogoTableModel obtenerModelo() {
        return catalogoTableModel;
    }

    @Override
    public void limpiarModelo() {
        catalogoTableModel = null;
    }

    @Override
    public void setEditable(boolean esEditable) {
        catalogoTableModel.setEditable(esEditable);
    }

    class CatalogoTableModel extends DefaultTableModel {

        Catalogo catalogo;
        boolean editable = true;
        Object[] encabezado = {"Código", "Nombre", "Idioma", "Autor"};
        //private Collection<Titulo> titulos;
        private ArrayList<Titulo> listaTitulos = new ArrayList<Titulo>();

        public CatalogoTableModel(Catalogo catalogo) {
            super();
            this.catalogo = catalogo;
            Collection<Titulo> titulos = catalogo.getCatalogo().values();
            Object data[][] = new Object[titulos.size()][encabezado.length];

            int i = 0;
            for (Titulo titulo : titulos) {
                int j = 0;
                // Extraemos los apellidos
                data[i][j++] = titulo.getId().getDeweyCategoriaDewey() + "-" + titulo.getId().getIdApellido() + "-" + titulo.getId().getIdTitulo();
                data[i][j++] = titulo.getNombreTitulo();
                data[i][j++] = WordUtils.capitalizeFully(titulo.getIdioma6391().getIdioma6391());
                Set<Autor> autores = titulo.getAutors();
                Iterator<Autor> it = autores.iterator();
                int numAutores = autores.size();
                String autoresStr = "";
                if (numAutores > 0) {
                    Autor autor = it.next();
                    autoresStr = autor.getApellido1Autor() + ", " + autor.getNombreAutor();
                    if (numAutores > 1) {
                        autoresStr += " ...";
                    }
                } else {
                    autoresStr = "Sin autor";
                }

                data[i][j++] = autoresStr;

                listaTitulos.add(titulo);
                i++;
            }
            setDataVector(data, encabezado);
        }

        public boolean isCellEditable(int rowIndex, int columnIndex) {
            if (!editable) {
                return false;
            } else {
                return super.isCellEditable(rowIndex, columnIndex);
            }
        }

        public void addTitulo(Titulo titulo) {
            //titulos.add(titulo);
            listaTitulos.add(titulo);
        }

        public Titulo getTitulo(int pos) {
            return listaTitulos.get(pos);
        }

        public boolean isEditable() {
            return editable;
        }

        public void setEditable(boolean editable) {
            System.out.println("editable:" + editable);
            this.editable = editable;
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCatalogo = new javax.swing.JTable();
        jButtonAceptar = new javax.swing.JButton();
        jButtonMostrarFicha = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Catálogo general");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/images/catalogo_20.png"))); // NOI18N

        jTableCatalogo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableCatalogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCatalogoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCatalogo);

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jButtonMostrarFicha.setText("Mostrar ficha");
        jButtonMostrarFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarFichaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonAceptar)
                        .addGap(40, 40, 40)
                        .addComponent(jButtonMostrarFicha)
                        .addGap(220, 220, 220))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAceptar)
                    .addComponent(jButtonMostrarFicha))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jTableCatalogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCatalogoMouseClicked
        int pos = jTableCatalogo.getSelectedRow();
        boolean visible = pos > -1 ? true : false;
        jButtonMostrarFicha.setVisible(visible);
        //vGFichaTitulo.setVisible(true);
    }//GEN-LAST:event_jTableCatalogoMouseClicked

    private void jButtonMostrarFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarFichaActionPerformed
        int filaSeleccionada = jTableCatalogo.getSelectedRow();
        System.out.println(filaSeleccionada);
        if (filaSeleccionada > -1) {
            System.out.println("--:" + catalogoTableModel.getTitulo(filaSeleccionada));
            vGFichaTitulo.fijarModelo(catalogoTableModel.getTitulo(filaSeleccionada));
            vGFichaTitulo.setEditable(false);
            vGFichaTitulo.setVisible(true);
        }

    }//GEN-LAST:event_jButtonMostrarFichaActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonMostrarFicha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCatalogo;
    // End of variables declaration//GEN-END:variables
}
