package H2;
// Generated 28-nov-2011 22:36:46 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Plantilla generated by hbm2java
 */
public class Plantilla  implements java.io.Serializable {


     private byte idPlantilla;
     private String nombrePlantilla;
     private Set usuarios = new HashSet(0);

    public Plantilla() {
    }

	
    public Plantilla(byte idPlantilla, String nombrePlantilla) {
        this.idPlantilla = idPlantilla;
        this.nombrePlantilla = nombrePlantilla;
    }
    public Plantilla(byte idPlantilla, String nombrePlantilla, Set usuarios) {
       this.idPlantilla = idPlantilla;
       this.nombrePlantilla = nombrePlantilla;
       this.usuarios = usuarios;
    }
   
    public byte getIdPlantilla() {
        return this.idPlantilla;
    }
    
    public void setIdPlantilla(byte idPlantilla) {
        this.idPlantilla = idPlantilla;
    }
    public String getNombrePlantilla() {
        return this.nombrePlantilla;
    }
    
    public void setNombrePlantilla(String nombrePlantilla) {
        this.nombrePlantilla = nombrePlantilla;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


