package H2;
// Generated 28-nov-2011 22:36:46 by Hibernate Tools 3.2.1.GA



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int dni;
     private Tipo tipo;
     private Plantilla plantilla;
     private String clave;
     private String nombreUsuario;
     private String apellido1Usuario;
     private String apellido2Usuario;
     private String email;
     private int telefono;
     private String direccion;
     private boolean isAdministrador;

    public Usuario() {
    }

	
    public Usuario(int dni, Tipo tipo, Plantilla plantilla, String clave, String nombreUsuario, String apellido1Usuario, String email, int telefono, String direccion, boolean isAdministrador) {
        this.dni = dni;
        this.tipo = tipo;
        this.plantilla = plantilla;
        this.clave = clave;
        this.nombreUsuario = nombreUsuario;
        this.apellido1Usuario = apellido1Usuario;
        this.email = email;
        this.telefono = telefono;
        this.direccion = direccion;
        this.isAdministrador = isAdministrador;
    }
    public Usuario(int dni, Tipo tipo, Plantilla plantilla, String clave, String nombreUsuario, String apellido1Usuario, String apellido2Usuario, String email, int telefono, String direccion, boolean isAdministrador) {
       this.dni = dni;
       this.tipo = tipo;
       this.plantilla = plantilla;
       this.clave = clave;
       this.nombreUsuario = nombreUsuario;
       this.apellido1Usuario = apellido1Usuario;
       this.apellido2Usuario = apellido2Usuario;
       this.email = email;
       this.telefono = telefono;
       this.direccion = direccion;
       this.isAdministrador = isAdministrador;
    }
   
    public int getDni() {
        return this.dni;
    }
    
    public void setDni(int dni) {
        this.dni = dni;
    }
    public Tipo getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Tipo tipo) {
        this.tipo = tipo;
    }
    public Plantilla getPlantilla() {
        return this.plantilla;
    }
    
    public void setPlantilla(Plantilla plantilla) {
        this.plantilla = plantilla;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getApellido1Usuario() {
        return this.apellido1Usuario;
    }
    
    public void setApellido1Usuario(String apellido1Usuario) {
        this.apellido1Usuario = apellido1Usuario;
    }
    public String getApellido2Usuario() {
        return this.apellido2Usuario;
    }
    
    public void setApellido2Usuario(String apellido2Usuario) {
        this.apellido2Usuario = apellido2Usuario;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public int getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(int telefono) {
        this.telefono = telefono;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public boolean isIsAdministrador() {
        return this.isAdministrador;
    }
    
    public void setIsAdministrador(boolean isAdministrador) {
        this.isAdministrador = isAdministrador;
    }




}


